### ISSUE TITLE
Skill set and about me sections

### ISSUE THREAD

**Issue by sanieni6** [yosaddis/Portfolio#3]
## Skill set and about me sections
Some comments about the last 5 commits:
+ kindly ensure the ident space of 2 spaces
+ Its advisable to follow semantic tag to make the code professional
+ Please make a transparent down arrow on the headline section as seen on the figma design.
+ kindly follow the linters advise adding the extension on your code editor.

**Comment by yosaddis** [comment]
@sanieni6 Thank you for your comment. All the issues are resolved on the latest version.
